### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SalvorinFex**
Adding 2 INO files for examples of the Blink_AnalogRead of teh
Leonardo/Micro and Pro Micro

### CODE REVIEW

**Comment by feilipu** [comment]
Kurt,
I'll do this by adding explanatory comments to the main examples.
https://github.com/feilipu/Arduino_FreeRTOS_Library/commit/f44a556b20f77632517fb51eb52e7f6261762702

I think adding separate additional files with different sub-names is going to make it a bit complex for those getting started.

Thanks for doing the testing on LEONARDO and MICRO too.

Phillip

**Comment by SalvorinFex** [comment]
You are most welcome.
This was my first attempt at a PR, but it still was I great learning experience.

**Comment by SalvorinFex** [comment]
HI, What about the changes in the sketch for the Pro Micro and the RXLED  instead of pin 13 part?
I guess an additional comment on how to change it would suffice.  And/Or a commented line that could replace it would work as well.

**Comment by feilipu** [comment]
It is already there... check the commit... https://github.com/feilipu/Arduino_FreeRTOS_Library/commit/f44a556b20f77632517fb51eb52e7f6261762702

The MICRO does not have a LED_BUILTIN available. For the MICRO board please substitute
the LED_BUILTIN definition with either LED_BUILTIN_RX or LED_BUILTIN_TX.
e.g. pinMode(LED_BUILTIN_RX, OUTPUT); etc.

**Comment by SalvorinFex** [comment]
Ohh, I seem to miss the comments sometimes, sorry to have bugged you...again.
Thanks again for you help, I will try some of the other FreeRTOS stuff, should be fun!

**Pull request closed without merging**
