### PR TITLE
Fix type mismatch in static allocation build

### PR DESCRIPTION
**Pull request by Floessie**
Hi Phillip,

One change was missing for static allocation builds.

Best,
Flössie

### CODE REVIEW

**Comment by Floessie** [comment]
Ping. 😉 

From my POV it's a no-brainer.

BTW: With static allocation, `Blink_AnalogRead` also compiles for ATtiny84/85 with some stack size tweaking (and a little change to `variantHooks.cpp`, as Dr. Azzy's [ATtinyCore](https://github.com/SpenceKonde/ATTinyCore) doesn't have `serialEventRun`).

**Comment by Floessie** [comment]
Hi Phillip,

I'm about to publish my [wrapper library](https://github.com/Floessie/frt) for inclusion in the Arduino Library Manager. As it's designed to work best with static allocation, it would be great if you could fix this problem, so that simply enabling `configSUPPORT_STATIC_ALLOCATION` will work without fuzz.

I hope my library will gain some traction for the Arduino_FreeRTOS_Library. Comments welcome.

Best,
Flössie

**Comment by Floessie** [comment]
[`frt`](https://github.com/Floessie/frt) is now available in the [Library Manager](https://github.com/arduino/Arduino/issues/7186).

**Comment by feilipu** [comment]
Sorry was AFK.

**Pull request merged**
